### ISSUE TITLE
Tracking Issue: Level Editor

### ISSUE THREAD

**Issue by hquil** [the-Glitchy-Galleon/pirate-jam-15#37]
### Basic Controls
- `cargo run --features editor -- editor` to launch
- `1` Selects the Terrain Tool
  - Left-Click to raise the ground elevation
  - Shift + Left-Click to lowerthe ground elevation
- `2` Selects the wall tool
  - Left-Click to raise the wall
  - Shift + Left-Click to lower the wall
- `3` Selects the UV tool
  - choose tile from the palette (use mousewheel and drag to navigate)
  - Tab to show tile palette in full-screen
  - Left-Click to paint
- `4` Opens the Object Editor
- WASD to move camera, right-click to pan
- CTRL+S to save (tilemap as .ron)
- CTRL+O to load
- CTRL+E to export (baked level as .level)
- CTRL+R to resize tilemap

### Editor
- [X] launch via `cargo run editor`
- [X] Save tilemap data as .ron files
- [X] Load tilemap data from .ron files
- [X] Raise/Lower Elevation
- [X] Generate Wall Meshes and preview collider
- [X] Generate Floor Mesh and heightfield collider
- [ ] Define palette of 3D meshes to be placed
- [ ] Place 3D Meshes on cube faces (incl. rotation)
- [x] Define palette and parameters of Game Objects to be placed
- [x] Place Object Markers on ground tiles
- [x] Parametrize Object Markers
- [x] Scene Export for the game
- [x] Resize Tilemap grid and indices
- [ ] Invisible Walls

### Bugfixes
- [x] Recalculate Normals

### Game
- [x] Scene Import
- [x] Object Construction from Markers

### Nice to haves
- [ ] Hold Click to use tools
- [ ] Terrain Flattening tool
- [ ] More resilient convex collider for wall meshes
- [ ] Autosave Feature
- [ ] Undo Feature
- [ ] "Color Picker"
